
const char* zircon_factory_game::get_component_name_by_enum(zircon_component_type_t component_type) const noexcept {
	switch (component_type) {

		case zircon_component_type_t::kComponentTypezircon_component_camera:
		{
			return zircon_component_camera::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_input:
		{
			return zircon_component_input::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_transform:
		{
			return zircon_component_transform::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_visibility:
		{
			return zircon_component_visibility::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_geometry:
		{
			return zircon_component_geometry::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_model:
		{
			return zircon_component_model::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_actor:
		{
			return zircon_component_actor::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_terrain:
		{
			return zircon_component_terrain::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_terrain_impl_cbt:
		{
			return zircon_component_terrain_impl_cbt::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_frustum:
		{
			return zircon_component_frustum::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_bounding_sphere:
		{
			return zircon_component_bounding_sphere::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_ui_surface:
		{
			return zircon_component_ui_surface::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_ui_camera:
		{
			return zircon_component_ui_camera::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_animation:
		{
			return zircon_component_animation::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_sdk_scene_name:
		{
			return zircon_component_sdk_scene_name::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_sdk_camera:
		{
			return zircon_component_sdk_camera::GetComponentName().c_str();
		}
	
		case zircon_component_type_t::kComponentTypezircon_component_sdk_input:
		{
			return zircon_component_sdk_input::GetComponentName().c_str();
		}
	
	default:
	{
		KOTEK_ASSERT(false, "Unsupported component type, did you register that in your enum aka did you create files? Because enum is autogenerated by CMake");
		return "UNSUPPORTED_COMPONENT_ENUM";
	}

}
}
